"""empty message

Revision ID: 095a30ffa4f1
Revises: 126b251062f2
Create Date: 2022-12-07 18:02:49.544409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '095a30ffa4f1'
down_revision = '126b251062f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('categoriaId', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('categoriaId')
    )
    op.create_table('subCategoria',
    sa.Column('subCategoriaId', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=True),
    sa.Column('categoria', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria'], ['categoria.categoriaId'], ),
    sa.PrimaryKeyConstraint('subCategoriaId')
    )
    op.create_table('producto',
    sa.Column('productoId', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('detalles', sa.String(length=200), nullable=False),
    sa.Column('precio', sa.String(length=200), nullable=False),
    sa.Column('vendedor', sa.Integer(), nullable=True),
    sa.Column('subCategoria', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subCategoria'], ['subCategoria.subCategoriaId'], ),
    sa.ForeignKeyConstraint(['vendedor'], ['user.id'], ),
    sa.PrimaryKeyConstraint('productoId')
    )
    op.create_table('carrito',
    sa.Column('carritoId', sa.Integer(), nullable=False),
    sa.Column('producto', sa.Integer(), nullable=True),
    sa.Column('usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['producto'], ['producto.productoId'], ),
    sa.ForeignKeyConstraint(['usuario'], ['user.id'], ),
    sa.PrimaryKeyConstraint('carritoId')
    )
    op.create_table('favoritos',
    sa.Column('favoritoId', sa.Integer(), nullable=False),
    sa.Column('producto', sa.Integer(), nullable=True),
    sa.Column('usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['producto'], ['producto.productoId'], ),
    sa.ForeignKeyConstraint(['usuario'], ['user.id'], ),
    sa.PrimaryKeyConstraint('favoritoId')
    )
    op.create_table('imagenes',
    sa.Column('imgId', sa.Integer(), nullable=False),
    sa.Column('imgProducto', sa.String(length=200), nullable=True),
    sa.Column('producto', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['producto'], ['producto.productoId'], ),
    sa.PrimaryKeyConstraint('imgId')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imgAvatar', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('nombre', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('apellido', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('domicilio', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('localidad', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('provincia', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('CP', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('DNI', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('DNI')
        batch_op.drop_column('CP')
        batch_op.drop_column('provincia')
        batch_op.drop_column('localidad')
        batch_op.drop_column('domicilio')
        batch_op.drop_column('apellido')
        batch_op.drop_column('nombre')
        batch_op.drop_column('imgAvatar')

    op.drop_table('imagenes')
    op.drop_table('favoritos')
    op.drop_table('carrito')
    op.drop_table('producto')
    op.drop_table('subCategoria')
    op.drop_table('categoria')
    # ### end Alembic commands ###
